#!/usr/bin/env bash
# One-shot install of SolarScope on a fresh Ubuntu 24.04 EC2 instance.
# Re-running is safe: it pulls the latest code, re-downloads the model and restarts the service.
#   curl -fsSL https://raw.githubusercontent.com/Pai05/solarscope/main/infra/setup.sh | sudo bash
# With model weights from S3 (remembered for later runs):
#   curl -fsSL .../infra/setup.sh | sudo MODEL_S3_PREFIX=s3://<bucket>/models bash
set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/Pai05/solarscope.git}"
APP_DIR=/opt/solarscope
APP_USER=solarscope
CONF=/etc/solarscope.conf

[ -f "$CONF" ] && . "$CONF"
MODEL_S3_PREFIX="${MODEL_S3_PREFIX:-}"
[ -n "$MODEL_S3_PREFIX" ] && echo "MODEL_S3_PREFIX=$MODEL_S3_PREFIX" > "$CONF"

echo "== packages"
apt-get update -y
apt-get install -y git python3-venv python3-pip unzip curl

echo "== swap (2 GB) so model loading does not OOM on a 2 GB instance"
if ! swapon --show | grep -q /swapfile; then
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  grep -q '^/swapfile' /etc/fstab || echo '/swapfile none swap sw 0 0' >> /etc/fstab
fi

echo "== AWS CLI (uses the instance IAM role; no keys on disk)"
if ! command -v aws >/dev/null; then
  curl -fsSL "https://awscli.amazonaws.com/awscli-exe-linux-$(uname -m).zip" -o /tmp/awscliv2.zip
  unzip -q -o /tmp/awscliv2.zip -d /tmp
  /tmp/aws/install --update
fi

echo "== app user and code"
id -u "$APP_USER" >/dev/null 2>&1 || useradd --system --create-home --shell /usr/sbin/nologin "$APP_USER"
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" pull --ff-only
else
  git clone "$REPO_URL" "$APP_DIR"
fi
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

echo "== model weights"
if [ -n "$MODEL_S3_PREFIX" ]; then
  # Runs as root with the instance role; no access keys on disk.
  mkdir -p "$APP_DIR/models"
  aws s3 cp "${MODEL_S3_PREFIX%/}/solarscope.onnx" "$APP_DIR/models/solarscope.onnx"
  aws s3 cp "${MODEL_S3_PREFIX%/}/solarscope.json" "$APP_DIR/models/solarscope.json" || true
  chown -R "$APP_USER:$APP_USER" "$APP_DIR/models"
else
  echo "MODEL_S3_PREFIX not set: running without a model (manual painting still works)"
fi

echo "== python venv"
sudo -u "$APP_USER" python3 -m venv "$APP_DIR/.venv"
sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q --upgrade pip
sudo -u "$APP_USER" "$APP_DIR/.venv/bin/pip" install -q -r "$APP_DIR/requirements.txt"

echo "== systemd service (app on 127.0.0.1:8000, behind Caddy)"
cat > /etc/systemd/system/solarscope.service <<EOF
[Unit]
Description=SolarScope FastAPI app
After=network-online.target
Wants=network-online.target

[Service]
User=$APP_USER
WorkingDirectory=$APP_DIR
EnvironmentFile=-$APP_DIR/.env
ExecStart=$APP_DIR/.venv/bin/uvicorn backend.app:app --host 127.0.0.1 --port 8000 --workers 1 --proxy-headers
Restart=always
RestartSec=3

[Install]
WantedBy=multi-user.target
EOF

systemctl daemon-reload
systemctl enable solarscope
systemctl restart solarscope

echo "== Caddy: HTTPS (needed for camera/AR in browsers) on <public-ip>.sslip.io, plain HTTP on the IP"
if ! command -v caddy >/dev/null; then
  apt-get install -y debian-keyring debian-archive-keyring apt-transport-https gnupg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/gpg.key' | gpg --dearmor --yes -o /usr/share/keyrings/caddy-stable-archive-keyring.gpg
  curl -1sLf 'https://dl.cloudsmith.io/public/caddy/stable/debian.deb.txt' > /etc/apt/sources.list.d/caddy-stable.list
  apt-get update -y
  apt-get install -y caddy
fi
# Public IP from the EC2 metadata service (IMDSv2); sslip.io resolves a-b-c-d.sslip.io to a.b.c.d.
TOKEN=$(curl -fsS -X PUT http://169.254.169.254/latest/api/token -H "X-aws-ec2-metadata-token-ttl-seconds: 60" || true)
PUBLIC_IP=$(curl -fsS -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4 || true)
if [ -n "$PUBLIC_IP" ]; then
  HOST="${PUBLIC_IP//./-}.sslip.io"
  cat > /etc/caddy/Caddyfile <<EOF
# Generated by infra/setup.sh. HTTPS host (certificate obtained automatically by Caddy):
$HOST {
	encode gzip
	reverse_proxy 127.0.0.1:8000
}
# Plain HTTP on the bare IP keeps working (no redirect), e.g. http://$PUBLIC_IP/
http:// {
	encode gzip
	reverse_proxy 127.0.0.1:8000
}
EOF
else
  HOST=""
  echo "Could not read the public IP; serving plain HTTP only"
  printf 'http:// {\n\tencode gzip\n\treverse_proxy 127.0.0.1:8000\n}\n' > /etc/caddy/Caddyfile
fi
systemctl enable caddy
systemctl restart caddy

sleep 3
systemctl --no-pager --lines=5 status solarscope || true
echo "== local check"
curl -fsS http://127.0.0.1:8000/health && echo
curl -fsS http://127.0.0.1/health >/dev/null && echo "Caddy proxy OK"
echo "Done."
echo "  App:            http://${PUBLIC_IP:-<public-ip>}/"
[ -n "$HOST" ] && echo "  HTTPS (for AR): https://$HOST/   (first visit may take ~30 s while the certificate is issued)"
